/**
 * ─────────────────────────────────────────────
 * Created by @soyEnriqueRocha
 * In collaboration with @tododeia
 * Redistribution without credit is not permitted.
 * ─────────────────────────────────────────────
 */

import fs from "node:fs";
import path from "node:path";

const OUTPUT_SIGNATURE = "# Scaffolded with the Project Builder by @soyEnriqueRocha x @tododeia";

function safeProjectDirName(name) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function generateStarterProject(baseDir, rawName, options = {}) {
  const normalized = safeProjectDirName(rawName || "my-kaizen-project");
  const targetDir = path.resolve(baseDir, normalized);
  const focus = typeof options.focus === "string" ? options.focus : "web-app";
  const profile = typeof options.profile === "string" ? options.profile : "default";

  if (fs.existsSync(targetDir)) {
    throw new Error(`target already exists: ${targetDir}`);
  }

  fs.mkdirSync(path.join(targetDir, "src"), { recursive: true });

  fs.writeFileSync(
    path.join(targetDir, "README.md"),
    [
      OUTPUT_SIGNATURE,
      "",
      `# ${rawName || "My Kaizen Project"}`,
      "",
      `Focus: ${focus}`,
      `Profile: ${profile}`,
      "",
      "Generated by Kaizen.",
      "",
      "Built with credit preserved.",
      "",
    ].join("\n"),
    "utf8",
  );

  fs.writeFileSync(
    path.join(targetDir, "src", "main.js"),
    [
      "// Scaffolded with the Project Builder by @soyEnriqueRocha x @tododeia",
      "",
      "console.log(\"hello from your kaizen starter project\");",
      "",
    ].join("\n"),
    "utf8",
  );

  fs.writeFileSync(
    path.join(targetDir, "index.html"),
    [
      "<!-- Scaffolded with the Project Builder by @soyEnriqueRocha x @tododeia -->",
      "<!doctype html>",
      "<html lang=\"en\">",
      "  <head>",
      "    <meta charset=\"UTF-8\" />",
      "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
      `    <title>${rawName || "Kaizen Project"}</title>`,
      "  </head>",
      "  <body>",
      "    <h1>Kaizen Starter</h1>",
      "    <script src=\"./src/main.js\"></script>",
      "  </body>",
      "</html>",
      "",
    ].join("\n"),
    "utf8",
  );

  return targetDir;
}
